### ISSUE TITLE
heres the info 

### ISSUE THREAD

**Issue by skullbro** [alfonsojon/roblox-linux-wrapper#92] opened 2015-04-22 19:13 UTC
ok i scaned your git but it says E: Invalid operation git when i type sudo apt-get and then your code and when i just copy it it says no such file.

**Comment by alfonsojon** [comment] 2015-04-22 19:22
Did you install git?

**Comment by skullbro** [comment] 2015-04-22 19:33
wait i had to install git to gegt the thing

**Comment by skullbro** [comment] 2015-04-22 19:33
oooooohhhhhhhhhhhhhh

**Comment by skullbro** [comment] 2015-04-22 19:35
how do i install that on linux

**Comment by GLolol** [comment] 2015-04-22 23:02
`sudo apt-get install git`, if you're on Ubuntu or anything similar.

**Comment by skullbro** [comment] 2015-04-23 10:54
hmm.. ok thanks james

**Comment by skullbro** [comment] 2015-04-23 10:56
wait thjen what do i type

**Comment by skullbro** [comment] 2015-04-23 11:08
i typed what you said then it needs another code whats that

**Comment by NokiaGuy** [comment] 2015-04-23 11:16
The terminal will ask for your password after that... @skullbro

**Comment by skullbro** [comment] 2015-04-23 20:44
hmm....  i tried sudo apt-get install git and every code not at once but 1
at a time

**Comment by GLolol** [comment] 2015-04-23 21:53
I don't understand what you mean.

**Comment by InvalidInvoke** [comment] 2015-04-23 22:26
As Nokia stated, the terminal is asking for your password.
The thing that you log in with.
You had to create a password during installation; the terminal needs that to continue, enter that when it asks after you run sudo apt-get install git
@skullbro

**Comment by skullbro** [comment] 2015-04-24 10:51
wait my computer password or my  account password

**Comment by NokiaGuy** [comment] 2015-04-24 11:08
When you installed Linux it would've asked for a single password. Use that password.

**Comment by GLolol** [comment] 2015-04-26 17:38
Closing as not a bug.

**Closed** 2015-04-26 17:38 UTC
Labels: invalid, question

**Comment by skullbro** [comment] 2015-05-05 20:28
oh so i typed it wrong ok ill try so i do my github pasdsword right?

**Comment by skullbro** [comment] 2015-05-05 20:40
oh know i see mny problem it says i need a newer veersion of wine how do i uptdate it

**Comment by GLolol** [comment] 2015-05-05 21:05
https://www.winehq.org/download/ubuntu

**Comment by skullbro** [comment] 2015-05-08 00:06
so whats the command to install the wine? i tried sudo apt-get-repository
*ppa:ubuntu-wine/ppa*

**Comment by GLolol** [comment] 2015-05-08 01:01
From the WineHQ page:

## Alternative Command Line Instructions for Installing Wine:

It is also possible to add the PPA and install via the terminal. This may be useful on Ubuntu flavors and derivatives.

*sudo add-apt-repository ppa:ubuntu-wine/ppa*

Then update APT package information by running '**sudo apt-get update**'. You can now install Wine by typing '**sudo apt-get install wine1.7**'.

----

I cannot see how this is not clear enough. Help us help you.
