### ISSUE TITLE
Experiencing errors on latest WINE and latest clone from GIT trunk

### ISSUE THREAD

**Issue by youknowwho** [alfonsojon/roblox-linux-wrapper#97] opened 2015-05-03 01:05 UTC
Hello,

First and foremost, I wanted to extend my utmost gratitude to the developers and maintainers of this repository. My hat is off to you for your excellence. My family and I have enjoyed many wonderful hours with Roblox under this project.

I did have a question about getting Roblox running again. Recently, I wasn't able to run Roblox; I am getting the same error on two different systems. The error message is as follows:

An unexpected error occurred and ROBLOX needs to quit. We're sorry!

Please forgive me for not being knowledgeable about what other data needs to accompany the error message; I am very new at posting reports. I can at least share the system information:

1. This is a gentoo GNU/Linux operating system
2. The wine version is: wine-1.7.40 (Staging)

I would definitely be happy proceed in supporting the efforts to troubleshoot this scenario. Please let me know your thoughts or ideas.

Kind thanks again for your work on this project!

Best Regards,

You_Know_Who

**Comment by NokiaGuy** [comment] 2015-05-03 07:08
I can confirm this, same exact issue. 


OP didn't mention it, but also occurs w/ Studio as well.

**Comment by alfonsojon** [comment] 2015-05-04 16:27
I'll need to look into this when I get the chance. Is there any specific information required for reproducing, or does it "just happen"?

Best of luck, thank you for the report :)

**Comment by youknowwho** [comment] 2015-05-05 03:13
THank you so much for your help with it and for your thoughts.

So here's how things go:

1. First, I install the game. The rlw.sh script installs the programs. The GUI returns that Roblox was installed successfully.
2. Then I launch the rlw.sh script to play the game.
3. The GUI comes up and asks "What option would you like?
4. I select the default "Play Roblox" and then click "OK"
5. The Firefox brower opens, and opens to the "http://www.roblox.com/games/?SortFilter=default&TimeFilter=0&GenreFilter=1" page.
6. I click on one of the games. For example, the Pizza place.
7. The pizza place page comes up. I click the "play" button. I choose a character (boy).
8. The games seems like it's going to load.
9. I see the following messages while it is loading:
Roblox is updating
The Server is ready joining the game <---This is where the error message dialogue appears:
An unexpected error has occurred and ROBLOX needs to quit. We're sorry!

This time, I collected the terminal output. Maybe this would help you identify what I am doing wrong.

Many thanks for this project again!

Best Regards,

YKW





./rlw.sh
Roblox Linux Wrapper v2015.04.16-13-g8985e0d-master
Generating desktop file...

[Desktop Entry]
Comment=Play Roblox
Name=Roblox Linux Wrapper
Exec=/usr/games/roblox/roblox-linux-wrapper/rlw.sh
Actions=Support;RFAGroup;
GenericName=Building Game
Icon=/usr/games/roblox/roblox-linux-wrapper/roblox.png
Categories=Game;
Type=Application

[Desktop Action Support]
Name=GitHub Support Ticket
Exec=xdg-open "https://github.com/alfonsojon/roblox-linux-wrapper/issues/new"

[Desktop Action RFAGroup]
Name=Roblox for All
Exec=xdg-open "http://www.roblox.com/Groups/group.aspx?gid=292611"

Finished generating desktop file. You can now install this desktop file via the command: xdg-desktop-menu install --novendor --mode user roblox.desktop
Not automatically overwriting the .desktop file; the epoch version seems up to date (rlw_epoch=1).
Checking for updates... You will need to restart the script afterwards for updates to apply, if there are any.
Already up-to-date.
 > begin roblox-install ()
---
 > end roblox-install ()
---
 > begin main ()
---
 > begin playerwrapper ()
---
 > begin rwine ()
---
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
regsvr32: Successfully registered DLL '/home/david/.wine/drive_c/users/david/Local Settings/Application Data/RobloxVersions/version-957ce0cc47814d39/RobloxProxy.dll'
fixme:msvcrt:__clean_type_info_names_internal (0x1001c398) stub
regsvr32: Successfully installed DLL '/home/david/.wine/drive_c/users/david/Local Settings/Application Data/RobloxVersions/version-957ce0cc47814d39/RobloxProxy.dll'
fixme:msvcrt:__clean_type_info_names_internal (0x1001c398) stub
 > begin rwineserver ()
---
 > end rwineserver ()
---
 > end rwine ()
---
 > begin rwine ()
---
fixme:winediag:start_process Wine Staging is a testing version containing experimental patches.
fixme:winediag:start_process Please report bugs at http://bugs.wine-staging.com (instead of winehq.org).
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:process:SetProcessDEPPolicy (1): stub
fixme:iphlpapi:NotifyAddrChange (Handle 0x67fe8b0, overlapped 0x67fe894): stub
fixme:winsock:WSCGetProviderPath ({e70f1aa0-ab8b-11cf-8ca3-00805f48a192} 0x72fe6ac 0x72fe66c 0x72fe698) Stub!
fixme:winsock:WSCGetProviderPath ({e70f1aa0-ab8b-11cf-8ca3-00805f48a192} 0x72fe6ac 0x72fe66c 0x72fe698) Stub!
fixme:winsock:WSCGetProviderPath ({11058240-be47-11cf-95c8-00805f48a192} 0x72fe6ac 0x72fe66c 0x72fe698) Stub!
fixme:winsock:WSCGetProviderPath ({11058241-be47-11cf-95c8-00805f48a192} 0x72fe6ac 0x72fe66c 0x72fe698) Stub!
fixme:winsock:WSCGetProviderPath ({11058241-be47-11cf-95c8-00805f48a192} 0x72fe6ac 0x72fe66c 0x72fe698) Stub!
fixme:advapi:RegisterTraceGuidsW (0x1c1f9d1, 0x69f0500, {509962e0-406b-46f4-99ba-5a009f8d2225}, 3, 0x663e740, (null), (null), 0x69f0530): stub
fixme:d3d:wined3d_dxtn_init Wine cannot find the txc_dxtn library, DXTn software support unavailable.
fixme:wbemprox:client_security_SetBlanket 0xf62aa6e8, 0x13a0b8, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0xf62aa6e8
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:imm:ImmReleaseContext (0x1005a, 0x142738): stub
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
err:ole:CoGetClassObject class {e77cc89b-7401-4c04-8ced-149db35add04} not registered
err:ole:CoGetClassObject class {e77cc89b-7401-4c04-8ced-149db35add04} not registered
err:ole:CoGetClassObject no class object {e77cc89b-7401-4c04-8ced-149db35add04} could be created for context 0x3
fixme:alsa:AudioSessionControl_SetGroupingParam (0x146f88)->({f20833cb-61e5-4660-bd4f-110f5c0585cd}, (null)) - stub
fixme:alsa:AudioSessionControl_SetGroupingParam (0x146f88)->({00000000-0000-0000-0000-000000000000}, (null)) - stub
fixme:alsa:AudioSessionControl_UnregisterAudioSessionNotification (0x146f88)->(0x8654dc0) - stub
fixme:advapi:TraceEvent 0 0x32f704
fixme:resource:GetGuiResources (0xffffffff,0): stub
fixme:win:FlashWindowEx 0x32edfc
fixme:imm:ImmGetOpenStatus (0x142738): semi-stub
err:ole:CoGetClassObject class {f7747266-777d-4f61-a175-dd5adf1e37df} not registered
err:ole:CoGetClassObject no class object {f7747266-777d-4f61-a175-dd5adf1e37df} could be created for context 0x1
fixme:advapi:TraceEvent 0 0x32c12c
err:ole:CoGetClassObject class {f7747266-777d-4f61-a175-dd5adf1e37df} not registered
err:ole:CoGetClassObject no class object {f7747266-777d-4f61-a175-dd5adf1e37df} could be created for context 0x1
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:console:AttachConsole stub ffffffff
fixme:process:SetProcessDEPPolicy (1): stub
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x12e3b8, L"RobloxGameUpdater": stub
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x12e628, L"RobloxGameUpdater": stub
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:ole:CoUninitialize Mismatched CoUninitialize
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:win:FlashWindowEx 0x3269ac
fixme:mstask:MSTASK_ITaskScheduler_Delete 0x12ed00, L"RobloxGameUpdater": stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb04 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f954 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fda0 1 C) semi-stub
C:\users\david\Local Settings\Application Data\Roblox\logs\
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f51c 1 C) semi-stub
fixme:d3d:wined3d_dxtn_init Wine cannot find the txc_dxtn library, DXTn software support unavailable.
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f620 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f668 1 C) semi-stub
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
fixme:wininet:IsDomainLegalCookieDomainW (L"roblox.com", L"www.roblox.com") semi-stub
fixme:avrt:AvSetMmThreadCharacteristicsW (L"Audio",0x582e9dc): stub
wine: Call from 0x7b83cfbe to unimplemented function d3d11.dll.D3D11CreateDeviceAndSwapChain, aborting
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpWithDataSegs
fixme:win:FlashWindowEx 0x32ee5c
fixme:msvcrt:__clean_type_info_names_internal (0x1537b78) stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fb04 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f954 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fda0 1 C) semi-stub
C:\users\david\Local Settings\Application Data\Roblox\logs\
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33f51c 1 C) semi-stub
Uploading C:\users\david\Local Settings\Application Data\Roblox\logs\log_5B475 0, 194, 0, 59009.Client.dmp
Uploading C:\users\david\Local Settings\Application Data\Roblox\logs\log_5B475.txt
Uploading C:\users\david\Local Settings\Application Data\Roblox\logs\log_5B475_G3D.txt
Uploading C:\users\david\Local Settings\Application Data\Roblox\logs\log_5B475_CrashReporter_WatcherThreadFunc_118.txt
fixme:msvcrt:__clean_type_info_names_internal (0x1537b78) stub
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
err:wininet:HTTP_ParseDate unexpected date format L"-1"
fixme:advapi:TraceEvent 0 0x32f998
fixme:msvcrt:__clean_type_info_names_internal (0xa45dc00) stub
fixme:msvcrt:__clean_type_info_names_internal (0x73443a4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x73a0834) stub
fixme:msvcrt:__clean_type_info_names_internal (0x72f36bc) stub
fixme:msvcrt:__clean_type_info_names_internal (0x39c398) stub
err:ole:CoUninitialize Mismatched CoUninitialize
fixme:msvcrt:__clean_type_info_names_internal (0x116844f4) stub
fixme:msvcrt:__clean_type_info_names_internal (0xe0cd0c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x37335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x793294) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a9ee0d4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a8c6384) stub
fixme:msvcrt:__clean_type_info_names_internal (0x96cb4c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x361a9c) stub
fixme:advapi:TraceEvent 0 0x32f9b4
fixme:font:RemoveFontMemResourceEx (0x8772a639) stub
fixme:font:RemoveFontMemResourceEx (0x87733fd1) stub
fixme:font:RemoveFontMemResourceEx (0x877c7219) stub
fixme:font:RemoveFontMemResourceEx (0x87784b91) stub
fixme:font:RemoveFontMemResourceEx (0x87796e69) stub
fixme:font:RemoveFontMemResourceEx (0x877e5769) stub
fixme:font:RemoveFontMemResourceEx (0x877ee249) stub
fixme:msvcrt:__clean_type_info_names_internal (0x38a524) stub
fixme:msvcrt:__clean_type_info_names_internal (0x28844f4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x118cd0c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x34335c) stub
fixme:msvcrt:__clean_type_info_names_internal (0xba3294) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a9ee0d4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x4a8c6384) stub
fixme:msvcrt:__clean_type_info_names_internal (0x80cb4c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x10021a9c) stub
 > begin rwineserver ()
---
 > end rwineserver ()
---
 > end rwine ()
---
 > end playerwrapper ()
---
 > begin main ()
---
 > end main ()
---
 > end main ()
---

**Comment by GLolol** [comment] 2015-05-05 15:25
You can wrap the logs with two sets of \`\`\` to prevent it from being formatted as titles. I've edited your comment to do that for you this time. :)

**Comment by alfonsojon** [comment] 2015-05-06 15:37
@GLolol I cannot do any investigation, as I'm busy with quite a bit (college starting in about two weeks, graduation, etc), but I believe this issue is due to a new version of the Visual Studio C++ Runtime being used. Can you look into the msvcrt###.dll files, and let me know which ones are present and not overridden by a flag? Thanks!

**Comment by GLolol** [comment] 2015-05-06 17:06
msvcrt is the **C** library, not a C++ library. There aren't any version numbers involved. The logs seem to suggest stubs, Windows API features Wine hasn't implemented yet.

**Comment by Z0MBIE2** [comment] 2015-05-06 22:46
This is the same issue I have, although more detailed.

**Comment by alfonsojon** [comment] 2015-05-07 05:28
@GLolol I mean the numbers following the runtime name, such as `msvcrt90.dll`.

**Comment by GLolol** [comment] 2015-05-07 14:03
@alfonsojon I don't see how this is relevant.

**Comment by alfonsojon** [comment] 2015-05-07 16:39
@GLolol Long story short, try running with `WINEDLLOVERRIDES="msvcp110.dll,msvcr110.dll=n,b"`

**Comment by alfonsojon** [comment] 2015-05-09 21:26
Edit: See discussion on [this commit](https://github.com/alfonsojon/roblox-linux-wrapper/commit/f76b8946a509469935e88ccf6166a5312a373468), it reveals that this seems to be a DirectX-related issue, and the game currently does work in wine-staging. There is a patched script there, if anyone would like to test it. I do not wish to deploy it until I can verify that it is working, as it requires a change in dependencies.

**Comment by GLolol** [comment] 2015-05-10 18:33
Closing as a duplicate of #96.

**Closed by GLolol** 2015-05-10 18:33 UTC
Labels: duplicate, wine-bug
