### ISSUE TITLE
Wont Play

### ISSUE THREAD

**Issue by masterdome** [alfonsojon/roblox-linux-wrapper#38] opened 2015-02-23 00:54 UTC
When i clicked play it loaded and then said  The program RobloxPlayerBeta.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience.
And then at the bottom This can be caused by a problem in the program or a deficiency in Wine. You may want to check the Application Database for tips about running this application.

**Comment by alfonsojon** [comment] 2015-02-24 15:11
Duplicate of #31

**Closed by alfonsojon** 2015-02-24 15:11 UTC
