### ISSUE TITLE
NEW ANNOYING Error

### ISSUE THREAD

**Issue by Triggatomic** [alfonsojon/roblox-linux-wrapper#60] opened 2015-03-26 14:38 UTC
Everytime I click play it just says to allow but I can't. 
When I try Legacy mode it crashes.
Help

**Comment by ArtinPerosteck** [comment] 2015-03-26 17:10
Exact same issue here.

**Comment by Triggatomic** [comment] 2015-03-26 20:59
Someone help???

**Comment by racquelL** [comment] 2015-03-27 01:35
ok no one is paying attention to my issues?? why?

**Comment by alfonsojon** [comment] 2015-03-27 04:54
Duplicate of #56. Also, this should be fixed in 20150326.

**Closed by alfonsojon** 2015-03-27 04:54 UTC

**Comment by alfonsojon** [comment] 2015-03-27 05:01
@racquelL I try my best to support it, but I am not employed by Roblox. This program was made in my free time; I'm in high school and work daily after school. Given my schedule, it's hard to fix an issue the second it is found; however, I aim to get them fixed as soon as possible.

**Comment by racquelL** [comment] 2015-03-27 10:59
wow ok thank you...I am impressed!

**Comment by alfonsojon** [comment] 2015-03-27 13:40
@racquelL Thanks!
