### ISSUE TITLE
Firefox crashing, "Wine closed unsuccesfully" error, problem #2.

### ISSUE THREAD

**Issue by Z0MBIE2** [alfonsojon/roblox-linux-wrapper#112] opened 2015-05-22 23:47 UTC
Had a post recently concerning this issue, turned out to be a specific problem, fixed that, yet now it seems to happen due to another issue. 
```
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
err:ole:CoGetClassObject class {38be3000-dbf4-11d0-860e-00a024cfef6d} not registered
err:ole:CoGetClassObject no class object {38be3000-dbf4-11d0-860e-00a024cfef6d} could be created for context 0x1
err:ole:CoGetClassObject class {94297043-bd82-4dfd-b0de-8177739c6d20} not registered
err:ole:CoGetClassObject no class object {94297043-bd82-4dfd-b0de-8177739c6d20} could be created for context 0x1
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
wine: Call from 0x7b83b6ae to unimplemented function msvcr120.dll.copysignf, aborting
fixme:dbghelp:elf_search_auxv can't find symbol in module
[NPAPI 91] ###!!! ABORT: Aborting on channel error.: file c:\builds\moz2_slave\rel-m-esr38-w32_bld-0000000000\build\ipc\glue\MessageChannel.cpp, line 1584
[NPAPI 91] ###!!! ABORT: Aborting on channel error.: file c:\builds\moz2_slave\rel-m-esr38-w32_bld-0000000000\build\ipc\glue\MessageChannel.cpp, line 1584
wine: Unhandled exception 0x80000003 in thread 60 at address 0x10001aa1 (thread 0060), starting debugger...
fixme:ver:GetCurrentPackageId (0x33f9f4 (nil)): stub
```
(Removed the log item below about x20)
```
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
fixme:wininet:query_global_option Unknown dwOption 10
```
And heres the details from the firefox crash. 
```
Add-ons: %7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0.1
AvailablePageFile: 6088974336
AvailablePhysicalMemory: 2390474752
AvailableVirtualMemory: 4294770687
BIOS_Manufacturer: The Wine Project
BlockedDllList: 
BreakpadReserveAddress: 49283072
BreakpadReserveSize: 67108864
BuildID: 20150514102509
CrashTime: 1432337903
EMCheckCompatibility: true
FramePoisonBase: 00000000f0de0000
FramePoisonSize: 65536
InstallTime: 1432337882
Notes: D3D11 Layers? D3D11 Layers- D3D9 Layers? D3D9 Layers- 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: esr
StartupTime: 1432337882
SystemMemoryUsePercentage: 40
Theme: classic/1.0
Throttleable: 1
TotalPageFile: 8240029696
TotalPhysicalMemory: 4045729792
TotalVirtualMemory: 4294836223
URL: http://www.roblox.com/games?SortFilter=default&TimeFilter=0&GenreFilter=1
Vendor: Mozilla
Version: 38.0.1
Winsock_LSP: TCP/IP : 2 : 1 :  
 UDP/IP : 2 : 2 :  
 IPX : 2 : 2 :  
 SPX : 2 : 5 :  
 SPX II : 2 : 5 : 
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.
```
--- Edit ---
Crashed right after, so here's some more logs. 
```
fixme:wininet:get_proxy_autoconfig_url no support on this platform
fixme:wininet:query_global_option INTERNET_OPTION_PER_CONNECTION_OPTION stub
wine: Call from 0x7b83b6ae to unimplemented function msvcr120.dll.copysignf, aborting
fixme:dbghelp:elf_search_auxv can't find symbol in module
[NPAPI 83] ###!!! ABORT: Aborting on channel error.: file c:\builds\moz2_slave\rel-m-esr38-w32_bld-0000000000\build\ipc\glue\MessageChannel.cpp, line 1584
[NPAPI 83] ###!!! ABORT: Aborting on channel error.: file c:\builds\moz2_slave\rel-m-esr38-w32_bld-0000000000\build\ipc\glue\MessageChannel.cpp, line 1584
wine: Unhandled exception 0x80000003 in thread 58 at address 0x10001aa1 (thread 0058), starting debugger...
fixme:ver:GetCurrentPackageId (0x33f9f4 (nil)): stub
z0mbie2@Overdrive:~$ p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
0x10001aa1: int	$3
Modules:
Module	Address			Debug info	Name (107 modules)
PE	  340000-  35b000	Deferred        mozglue
PE	  360000-  395000	Deferred        sandboxbroker
PE	  3b0000-  3d2000	Deferred        robloxproxy
PE	  400000-  446000	Deferred        plugin-container
PE	  670000-  6f3000	Deferred        nprobloxproxy
PE	  900000- 2cc6000	Deferred        xul
PE	 2cd0000- 2e70000	Deferred        nss3
PE	10000000-10006000	Export          mozalloc
PE	4a800000-4a8cd000	Deferred        icuuc52
PE	4a900000-4aa0a000	Deferred        icuin52
PE	4ad00000-4b6ea000	Deferred        icudt52
ELF	7b800000-7ba62000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba62000	\               kernel32
ELF	7bc00000-7bce7000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bce7000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7e479000-7e49e000	Deferred        imm32<elf>
  \-PE	7e480000-7e49e000	\               imm32
ELF	7e4e2000-7e50b000	Deferred        libexpat.so.1
ELF	7e50b000-7e547000	Deferred        libfontconfig.so.1
ELF	7e547000-7e573000	Deferred        libpng12.so.0
ELF	7e573000-7e58d000	Deferred        libz.so.1
ELF	7e58d000-7e63d000	Deferred        libfreetype.so.6
ELF	7e659000-7e684000	Deferred        msacm32<elf>
  \-PE	7e660000-7e684000	\               msacm32
ELF	7e684000-7e708000	Deferred        rpcrt4<elf>
  \-PE	7e690000-7e708000	\               rpcrt4
ELF	7e708000-7e84b000	Deferred        ole32<elf>
  \-PE	7e720000-7e84b000	\               ole32
ELF	7e84b000-7e8c6000	Deferred        advapi32<elf>
  \-PE	7e860000-7e8c6000	\               advapi32
ELF	7e8c6000-7e9e5000	Deferred        gdi32<elf>
  \-PE	7e8d0000-7e9e5000	\               gdi32
ELF	7e9e5000-7eb41000	Deferred        user32<elf>
  \-PE	7ea00000-7eb41000	\               user32
ELF	7eb41000-7ebfa000	Deferred        winmm<elf>
  \-PE	7eb50000-7ebfa000	\               winmm
ELF	7ebfa000-7ec07000	Deferred        libnss_files.so.2
ELF	7ec07000-7ec13000	Deferred        libnss_nis.so.2
ELF	7ec13000-7ec2c000	Deferred        libnsl.so.1
ELF	7ef9e000-7efe4000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f6524000-f654c000	Deferred        mpr<elf>
  \-PE	f6530000-f654c000	\               mpr
ELF	f654c000-f65c9000	Deferred        wininet<elf>
  \-PE	f6560000-f65c9000	\               wininet
ELF	f65c9000-f6684000	Deferred        msvcr90<elf>
  \-PE	f65e0000-f6684000	\               msvcr90
ELF	f6684000-f67cc000	Deferred        msvcp90<elf>
  \-PE	f66c0000-f67cc000	\               msvcp90
ELF	f6812000-f6819000	Deferred        libxfixes.so.3
ELF	f6819000-f6824000	Deferred        libxcursor.so.1
ELF	f6824000-f6836000	Deferred        libxi.so.6
ELF	f6836000-f683a000	Deferred        libxcomposite.so.1
ELF	f683a000-f6845000	Deferred        libxrandr.so.2
ELF	f6845000-f6851000	Deferred        libxrender.so.1
ELF	f6851000-f6857000	Deferred        libxxf86vm.so.1
ELF	f6857000-f6879000	Deferred        libxcb.so.1
ELF	f6879000-f69c4000	Deferred        libx11.so.6
ELF	f69c4000-f69d9000	Deferred        libxext.so.6
ELF	f69f5000-f6a89000	Deferred        winex11<elf>
  \-PE	f6a00000-f6a89000	\               winex11
ELF	f6a89000-f6aa8000	Deferred        pdh<elf>
  \-PE	f6a90000-f6aa8000	\               pdh
ELF	f6aa8000-f6bed000	Deferred        oleaut32<elf>
  \-PE	f6ac0000-f6bed000	\               oleaut32
ELF	f6bed000-f6c05000	Deferred        wtsapi32<elf>
  \-PE	f6bf0000-f6c05000	\               wtsapi32
ELF	f6c05000-f6cd5000	Deferred        crypt32<elf>
  \-PE	f6c10000-f6cd5000	\               crypt32
ELF	f6cd5000-f6d0c000	Deferred        wintrust<elf>
  \-PE	f6ce0000-f6d0c000	\               wintrust
ELF	f6d0c000-f6d7d000	Deferred        setupapi<elf>
  \-PE	f6d20000-f6d7d000	\               setupapi
ELF	f6d7d000-f6db4000	Deferred        uxtheme<elf>
  \-PE	f6d80000-f6db4000	\               uxtheme
ELF	f6db4000-f6dc8000	Deferred        msimg32<elf>
  \-PE	f6dc0000-f6dc8000	\               msimg32
ELF	f6dc8000-f6e0c000	Deferred        usp10<elf>
  \-PE	f6dd0000-f6e0c000	\               usp10
ELF	f6e0c000-f6e86000	Deferred        shlwapi<elf>
  \-PE	f6e20000-f6e86000	\               shlwapi
ELF	f6e86000-f70bd000	Deferred        shell32<elf>
  \-PE	f6e90000-f70bd000	\               shell32
ELF	f70bd000-f70ec000	Deferred        netapi32<elf>
  \-PE	f70c0000-f70ec000	\               netapi32
ELF	f70ec000-f7113000	Deferred        iphlpapi<elf>
  \-PE	f70f0000-f7113000	\               iphlpapi
ELF	f7113000-f714c000	Deferred        ws2_32<elf>
  \-PE	f7120000-f714c000	\               ws2_32
ELF	f714c000-f7168000	Deferred        wsock32<elf>
  \-PE	f7150000-f7168000	\               wsock32
ELF	f7168000-f7270000	Deferred        msvcp120<elf>
  \-PE	f71a0000-f7270000	\               msvcp120
ELF	f7270000-f7340000	Deferred        msvcr120<elf>
  \-PE	f7290000-f7340000	\               msvcr120
ELF	f7347000-f74f4000	Deferred        libc.so.6
ELF	f74f4000-f74f9000	Deferred        libdl.so.2
ELF	f74fa000-f7517000	Deferred        libpthread.so.0
ELF	f7517000-f7520000	Deferred        libnss_compat.so.2
ELF	f7521000-f7525000	Deferred        libxinerama.so.1
ELF	f7525000-f752c000	Deferred        libxdmcp.so.6
ELF	f752c000-f7530000	Deferred        libxau.so.6
ELF	f7533000-f76e9000	Dwarf           libwine.so.1
ELF	f76eb000-f770d000	Deferred        ld-linux.so.2
ELF	f770d000-f770e000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	0000001d    0
	0000001c    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001b    0
	00000018    0
	00000017    0
	00000013    0
00000019 plugplay.exe
	0000001f    0
	0000001e    0
	0000001a    0
00000020 explorer.exe
	00000021    0
00000053 (D) C:\Program Files\Mozilla Firefox\plugin-container.exe
	00000058    0 <==
	00000054    0
```

**Comment by GLolol** [comment] 2015-05-23 01:43
Sorry for making you reopen, I just realized this is a duplicate of #105.

**Closed by GLolol** 2015-05-23 01:43 UTC
