### ISSUE TITLE
The new install/uninstall method is really buggy.

### ISSUE THREAD

**Issue by ghost** [alfonsojon/roblox-linux-wrapper#80] opened 2015-04-17 03:42 UTC
Seriously.

* Installing is a lot more advanced than it should be, not sure why you would make it more complicated.
* The "Reinstall ROBLOX" method doesn't work at all, corrupts everything and attempting to launch anything will result  in the "Wine has closed" error.
* Not sure why; but "Uninstall ROBLOX" has been removed, not sure why but was a lot easier then doing it manually. 

Ever since that fork update has also caused "Ubuntu 14.04 has encountered a fatal error" to pop up while installing.

**Comment by GLolol** [comment] 2015-04-17 05:10
The installation methods have really changed a lot throughout the last few updates. It's not backwards compatible. Yes, it's buggy. And it's frustrating to maintain.

> Installing is a lot more advanced than it should be, not sure why you would make it more complicated.

Right now, the only thing "installation" does is add a nice little `.desktop` entry to the current location of `rlw.sh`, so that it can be accessed from an Application Menu. The problem with is that they require a fixed path, and `rlw.sh` does NOT have a fixed path. The `.desktop` entries are thus generated on every run to make sure we're pointing to the right place. After doing this, it begins work on the Wineprefix. Reinstallation/Uninstallation only needs to purge those paths.

> The "Reinstall ROBLOX" method doesn't work at all, corrupts everything and attempting to launch anything will result in the "Wine has closed" error.

I can't reproduce.

> Not sure why; but "Uninstall ROBLOX" has been removed, not sure why but was a lot easier then doing it manually.

I'm not sure why either. Fixing it now?

**Comment by eprent** [comment] 2015-04-17 06:17
How do you update it now? It doesn't give me the update available prompt. @GLolol

**Comment by GLolol** [comment] 2015-04-17 06:19
`cd` into the script directory and run `git pull`.

**Comment by eprent** [comment] 2015-04-17 06:22
Does it autoupdate? "already up to date" and a update came out almost an hour ago @GLolol

**Comment by GLolol** [comment] 2015-04-17 14:38
It should autoupdate - the script runs `git pull` when it starts.

**Comment by alfonsojon** [comment] 2015-04-17 15:27
@eprent I removed the uninstaller because I thought it'd be easier to delete a folder and a file than to modify the script to try and find out where it's installed. @GLolol Should I revert back to the former installation mechanism, with the one-line install?

**Comment by GLolol** [comment] 2015-04-17 17:04
@alfonsojon The script wouldn't work that way where it currently stands.

**Comment by GLolol** [comment] 2015-04-17 17:34
@alfonsojon The script already knows where it exists, thanks to $BASH_SOURCE. This allows it to call commands/scripts in its own directory, and more.

**Comment by GLolol** [comment] 2015-04-17 19:14
I realize that the updater logic is flawed - The script calls git pull on run, but runs the older version of rlw.sh instead of hot loading the new one.

**Comment by dragonballz2k** [comment] 2015-04-18 02:15
@alfonsojon I was wondering would it be easier to use deb file it might make these a little more complicated, but we could control the wine version and what repo we want it from like how google chrome adds custom repo.

**Comment by GLolol** [comment] 2015-04-18 03:43
@dragonballz2k Sounds good to me. Drop the hacky installation clauses, install to `/usr/bin/`, and voila. I have a bit of packaging experience, and I don't see this being too hard.

Further modifications would be required for any form of installation. 

@ghost The "Wine has closed" error should be fixed in the latest commit 7a763ca7556f15185b34832c86682586615619ac. It's was a regression caused by [a wine bug](https://bugs.winehq.org/show_bug.cgi?id=29661), and not us - go figure.

**Closed by GLolol** 2015-04-18 03:43 UTC
