### ISSUE TITLE
Roblox Crash

### ISSUE THREAD

**Issue by lecraerocks** [alfonsojon/roblox-linux-wrapper#36] opened 2015-02-16 22:37 UTC
Ok, so I have a Thinkpad t410 laptop with Ubuntu 14.04 LTS and I installed your Roblox Linux Wrapper, but I am having some issues. The first issue, when I launch a game in Roblox (call of robloxia 5 , summer edition, and all others), the game launches, but just gives me a white screen, or loads slightly then crashes. Then I get an error saying "an unexpected error occured and roblox needs to quit! we're sorry!". I have tried resetting the wrapper back to defaults, but still no luck. If you could help me that would be great! Thanks!

**Comment by lecraerocks** [comment] 2015-02-16 22:46
UPDATE: a temple run game just worked " http://www.roblox.com/TEMPLE-RUN-TO-FREE-VIP-place?id=216005118 ". Might it be that it does not have as many connectors and blocks?

**Comment by alfonsojon** [comment] 2015-02-19 00:14
Can you run the one line command listed on the README (main page) in a terminal, and tell me what error is printed in the terminal?

**Comment by alfonsojon** [comment] 2015-02-19 00:16
Duplicate of bug #31.

**Closed by alfonsojon** 2015-02-19 00:16 UTC

**Comment by lecraerocks** [comment] 2015-02-19 17:59
bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)   I ran this command in the terminal and got: Roblox Linux Wrapper v20150206-staging
rmdir: failed to remove ‘/home/landen/.local/share/wineprefixes/roblox-wine-staging’: Directory not empty

(zenity:1180): Gdk-WARNING **: gdk_window_set_icon_list: icons too large 

It opened the Wrapper after telling me this. Sorry, I had not seen the other post. Thank you!

**Comment by alfonsojon** [comment] 2015-02-19 20:06
No problem.

**Comment by lecraerocks** [comment] 2015-02-19 20:48
Is this what you were wanting?

**Comment by alfonsojon** [comment] 2015-02-19 21:16
Try running this in a terminal:
```WINEPREFIX=$HOME/.local/share/wineprefixes/Roblox-wine-staging winetricks ddr=gdi```

**Comment by lecraerocks** [comment] 2015-02-19 21:18
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing w_do_call ddr=gdi
Executing load_ddr gdi
Setting Direct3D/DirectDrawRenderer to gdi
Executing winetricks_early_wine regedit C:\windows\Temp\_ddr=gdi\set-wined3d.reg


This is what I got.

**Comment by lecraerocks** [comment] 2015-02-19 21:21
After running the runline command that was on the frontpage I got the same error:

bash <(wget -q https://raw.githubusercontent.com/alfonsojon/roblox-linux-wrapper/master/rlw.sh -O -)
Roblox Linux Wrapper v20150206-staging
rmdir: failed to remove ‘/home/landen/.local/share/wineprefixes/roblox-wine-staging’: Directory not empty

(zenity:10102): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

**Comment by alfonsojon** [comment] 2015-02-21 06:30
Those are not errors, you can ignore those.

**Comment by lecraerocks** [comment] 2015-02-22 17:24
What should I do next then? Should I type something into terminal while the game is crashing?

**Comment by alfonsojon** [comment] 2015-02-24 15:13
No, see the progress on Bug #31. Many others are having the same problem, I'll let you know when I have a fix. Thank you for your reports, and I'm sorry the game does not work!

**Comment by lecraerocks** [comment] 2015-02-24 18:02
Ok, thank you for your help.
