### ISSUE TITLE
Roblox encountering an error

### ISSUE THREAD

**Issue by cocobuter** [alfonsojon/roblox-linux-wrapper#19] opened 2015-01-13 18:13 UTC
It is now saying an error is occuring when ever game launches. I'm sorry to be a nuscence.

**Comment by HJSR** [comment] 2015-01-13 20:54
When i try running Roblox it says: Runtime Error! Program C:\users\hjsr\Local Settings\Application Data\RobloxVersions\version-d2af929835a34f18\RobloxPlayerBeta.exe abnormal program termination.

**Comment by alfonsojon** [comment] 2015-01-14 03:27
@cocobuter No worries, you're not a nuisance! I'm glad to be providing support. @HJSR @cocobuter Try resetting it to defaults, as it now uses wine-staging.

**Comment by cocobuter** [comment] 2015-01-14 10:57
I have done installation process over again, and resetting it to defaults. Neither is working i believe it is a bug that is happening when the firefox roblox page launches the second window for the game and it crashes.

**Comment by alfonsojon** [comment] 2015-01-14 14:01
I'll take a look when I am off work tonight around 21:00.

**Comment by cocobuter** [comment] 2015-01-14 15:58
Okay thank you very much!

**Comment by RainboomDash** [comment] 2015-01-27 22:45
This might be a bug related to what has been currently happening where Linux doesn't see Roblox being installed, during a test I performed Studio is reconized, not Roblox Player.

**Comment by alfonsojon** [comment] 2015-01-28 04:04
This should be fixed in build 20150127c-staging. Can I get feedback as to whether or not this is the case? Thanks!

**Comment by RainboomDash** [comment] 2015-01-28 04:24
Confirmed that it does work fine with Unity (Ubuntu regular desktop) and GNOME. As said by you, GNOME does have the black box in Roblox Studio, otherwise I think the almighty, heroic Alfonsojon has fixed RLW.

**Comment by RainboomDash** [comment] 2015-01-28 04:25
You really had the scare on me when I first reported the problem and being diagnosed with my hard drive.

**Comment by alfonsojon** [comment] 2015-01-28 04:26
@RainboomDash If you would like, you can file a related bug under libmutter. https://launchpad.net/ubuntu/+source/mutter

Sorry about that, that generally doesn't happen unless there are worse underlying problems. My bad!

**Comment by alfonsojon** [comment] 2015-01-28 04:27
More information - Mutter is the compositioning-enabled window manager used extensively by GNOME Shell, and used as a base for Elementary OS's window manager Gala. As it affects both, the issue is probably due to libmutter-dev not liking something with Wine.

**Comment by alfonsojon** [comment] 2015-01-28 04:27
Closing as fixed, thanks for the feedback everyone!

**Comment by RainboomDash** [comment] 2015-01-28 04:27
I don't mean any disrespect, but you should have a team of selected testers to test a build before official release or something.

And, alright thanks.

**Comment by alfonsojon** [comment] 2015-01-28 04:28
@RainboomDash The problem is that I don't have any of them, and when I code blind (I sometimes have to code without testing, which is bad), I slip sometimes; however, 99% of the problems are usually syntax errors.

**Comment by alfonsojon** [comment] 2015-01-28 04:30
@RainboomDash Sorry to bother, but what would your Roblox username be, so we can discuss? I also am available via email.

**Comment by RainboomDash** [comment] 2015-01-28 04:31
My Roblox account name stands at "Masterzackjg", 2009 account :P 

Hey, I don't have much but I am donating a small amount, all I have, all for you for your hard work and dedication to us, the fans.

**Comment by alfonsojon** [comment] 2015-01-28 04:34
Alright, thanks a bunch!

**Closed by alfonsojon** 2015-01-28 04:34 UTC
Labels: bug

**Comment by LilNinja5181** [comment] 2015-03-29 15:46
I actually received this error again today for Roblox, I just installed it as I had to reinstall Ubuntu however, before Roblox worked without a problem but this time the error occurred again. I tried to run Roblox and it said: "Runtime error! Program: C:\users\minyoung\Local Settings\Application Data\RobloxVersions\version-f9d6d23b9blb466e\RobloxPlayerBeta.exe abnormal program termination Press OK to exit the program, or Cancel to start the Wine debbuger." I pressed Cancel and it wouldn't debug and also I reinstalled thinking that was the case. I think it might be because I'm on an old git version (1.9) as I could not upgrade because there was a problem in actually upgrading it. Please help and I apologize for taking up your time.
