### ISSUE TITLE
roblox keeps crashing when i play different games like laser tag or paintball (fixes)

### ISSUE THREAD

**Issue by stormchaser3000** [alfonsojon/roblox-linux-wrapper#33] opened 2015-02-11 05:01 UTC
sometimes robloxplayerbeta.exe crashes sometimes. (i will try to locate debug info)

**Comment by stormchaser3000** [comment] 2015-02-11 05:02
well i will get debug info later

**Comment by alfonsojon** [comment] 2015-02-12 17:03
I will look into this. Does anything trigger it, or is it random?

**Comment by alfonsojon** [comment] 2015-02-12 17:04
Duplicate of bug #31.

**Closed** 2015-02-12 17:04 UTC
Labels: duplicate
