### ISSUE TITLE
ROBLOX Crash.

### ISSUE THREAD

**Issue by 5shane1** [alfonsojon/roblox-linux-wrapper#35] opened 2015-02-15 16:07 UTC
Well, I just erased Ubuntu and install Ubuntu MATE Edition. Installed ROBLOX and still getting Crashes. I open Firefox (Under Wine) and I try to load a game, it gives me a white screen and says ROBLOX has crashed. I tried wiping my system over and over, but same the still problem. I had even did "Set ROBLOX to Defaults" or something and still didn't work.

**Comment by jreced** [comment] 2015-02-16 01:27
alfonsojon already knows about this. Its probably some Wine issue

**Comment by alfonsojon** [comment] 2015-02-16 06:40
Not enough info provided. What Linux distribution are you using, and what graphics card do you have?

**Comment by 5shane1** [comment] 2015-02-16 06:42
AMD Graphics and 14.04 MATE...

**Comment by alfonsojon** [comment] 2015-02-16 14:46
Do you have proprietary drivers installed? If you are not sure, see here:
https://help.ubuntu.com/community/BinaryDriverHowto/ATI

**Comment by alfonsojon** [comment] 2015-02-16 14:47
Run the following commands, actually.
```
sudo apt-get install fglrx-updates xvba-va-driver libva-glx1 libva-egl1 vainfo
sudo amdconfig --adapter=all --initial
```

**Comment by alfonsojon** [comment] 2015-02-16 14:48
Following that, reboot, and see if the game works.

**Comment by 5shane1** [comment] 2015-02-16 18:08
Now I'm getting green lines and ROBLOX used to work with games with a lot of bricks and connecters but now it doesn't. I can join any game with like just a baseplate but can't join games like big games.

**Comment by alfonsojon** [comment] 2015-02-19 00:15
Green lines?

**Comment by alfonsojon** [comment] 2015-02-19 00:17
Duplicate of bug #31.

**Closed by alfonsojon** 2015-02-19 00:17 UTC
Labels: bug, invalid
